services:
  backend:
    build:
      context: ./sklep-backend
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./sklep
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge