GET http://localhost:8080/products/

###

POST http://localhost:8080/products/
Content-Type: application/json

{
    "id": 3,
    "name": "Arbuz",
    "price": 15.0
}

###

PUT http://localhost:8080/products/1
Content-Type: application/json

{
    "id": 1,
    "name": "Pomarancza",
    "price": 3.5
}

###

DELETE http://localhost:8080/products/3